"""add visit_id to llm_cache table

Revision ID: 05d85be44341
Revises: 6920c86509c1
Create Date: 2025-09-01 14:44:34.727018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05d85be44341"
down_revision: Union[str, Sequence[str], None] = "6920c86509c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_cache", sa.Column("visit_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_llm_cache_visit_id"), "llm_cache", ["visit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_cache_visit_id"), table_name="llm_cache")
    op.drop_column("llm_cache", "visit_id")
    # ### end Alembic commands ###
