"""Add patient_id to llm_cache table

Revision ID: 6920c86509c1
Revises: e86e8e81d4b6
Create Date: 2025-09-01 14:18:27.840623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6920c86509c1"
down_revision: Union[str, Sequence[str], None] = "e86e8e81d4b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_cache", sa.Column("patient_id", sa.String(length=64), nullable=True))
    op.alter_column("llm_cache", "model_name", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("llm_cache", "input_tokens", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("llm_cache", "output_tokens", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("llm_cache", "total_cost", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.create_index(op.f("ix_llm_cache_patient_id"), "llm_cache", ["patient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_cache_patient_id"), table_name="llm_cache")
    op.alter_column("llm_cache", "total_cost", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("llm_cache", "output_tokens", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("llm_cache", "input_tokens", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("llm_cache", "model_name", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.drop_column("llm_cache", "patient_id")
    # ### end Alembic commands ###
